### ISSUE TITLE
Callbacks or function to customize fingerprint

### ISSUE THREAD

**Issue by tpitale** [SimonWoolf/sentry-logger-backend#3]
For error logs that we don't have access to in our own code (like process crashes) it would be cool to be able to munge the error with our own fingerprint processing so that sentry will properly group the same messages, even if they have different references or pids.

**Comment by tpitale** [comment]
One example message that sentry seems incapable of grouping:

```
GenServer :firmware_consumer terminating
** (stop) no connection
Last message: {:DOWN, #Reference<0.2443916546.1819803649.82881>, :process, {:firmware_notifier, :"node@127.0.0.1"}, :noconnection}
State: %{queue_name: :firmware}
```

**Comment by SimonWoolf** [comment]
Sure, sounds like a good idea. I unfortunately don't have time to work on feature requests for this project right now, but I'd be delighted to accept contributions if you feel like giving it a go yourself :slightly_smiling_face:

**Comment by tpitale** [comment]
@SimonWoolf Just sent a quick PR. Let me know what you think of the approach. Also open to any suggestions to make changes to clean up the code.
